### ISSUE TITLE
expose className attribute on Flippy

### ISSUE THREAD

**Issue by TrejGun** [sbayd/react-flippy#18]
Hello! thanks for your work!
We use Flippy with material ui so we use classNames instead of styles.
Unfortunately className is not supported on Flippy but supported on FrontSide and BackSide which is strange
please add support of className attribute to Flippy

**Comment by sbayd** [comment]
Hi,

Sorry for very late reply, I added this feature.

**Comment by TrejGun** [comment]
thanks!
