### ISSUE TITLE
A vue version?

### ISSUE THREAD

**Issue by andrewhl** [sbayd/react-flippy#3]
I would love if you or someone else could fork a version for vue. That would be amazing!

**Comment by sbayd** [comment]
Hey,

I will work on this and keep you updated in a few days!

Thank you.

**Comment by andrewhl** [comment]
@sbayd Any word on vue-flippy? :)

**Comment by sbayd** [comment]
Hey @andrewhl 

Months passed and unfortunately, I couldn't find any time to work on vue-flippy.

Any PR's are welcomed :)

**Comment by andrewhl** [comment]
@sbayd No worries! Maybe one day I'll have time :)
