### ISSUE TITLE
`isFlipped` as a prop

### ISSUE THREAD

**Issue by slig** [sbayd/react-flippy#4]
Hi,

I believe a `isFlipped` prop would be useful to control the component from outside in a declarative way (instead of the imperative `.toggle()`). For instance on a memory game where the state of all cards (if they're visible/invisible, flipped/unflipped) is on MobX/Redux.

PS: found your project on "Show HN".

**Comment by sbayd** [comment]
Hey,

Actually, it is already possible to use the component as a controlled by passing isFlipped prop, but it looks I forgot to add this info to documentation. 

I have updated the documentation and examples.

Thank you, Good catch!
