### ISSUE TITLE
NPM package issue

### ISSUE THREAD

**Issue by numbofathma** [sbayd/react-flippy#7]
`require("./styles.css"); ` in Flippy.js sholdn't be there, in the dist folder, from the npm package.
The above problem causes an issue in my app :(

In all the npm packages that I've used untill now you import the style in you project by hand.
Something like this:
import Flippy, { FrontSide, BackSide } from 'react-flippy';
import 'react-flippy/dist/styles.css';

**Comment by jean343** [comment]
Same here, I had to do `import Flippy, {FrontSide, BackSide} from 'react-flippy/src/lib';`
You could also try `styled-components`!

**Comment by ozgunarslantas** [comment]
I've had a similar issue in which I had to use the dreaded `!important` on a `box-shadow` property for the class that I provided via `className` property.

**Comment by codyburleson** [comment]
Same here...

![image](https://user-images.githubusercontent.com/7317733/115963274-d7306c00-a4db-11eb-8219-1e637797a1a7.png)

**Comment by sbayd** [comment]
Bundling system updated, the issue should be fixed now.
Thank you for reporting!
